### ISSUE TITLE
How to pass postcss options to this plugin?

### ISSUE THREAD

**Issue by marcinant** [RyanZim/postcss-uncss#1]
Hi, 

Could you explain how to set up postcss configuration options with this plugin?

I would like to use postcss with bootstrap and preserve media queries for mobile devices.

I use `postcss -c postcss.json`.

`postcss.json`:

```
{
    "use": ["postcss-uncss", "cssnano"],
    "output": "_includes/main.css",
    "autoprefixer": {
        "browsers": "> 5%"
    },
    "postcss-uncss": {
	"html": ["http://localhost:4000"],
	"options": {
	    "media": ["(min-width: 768px)", "(min-width: 992px)", "(min-width: 1200px)"]
	}
    }
}
```

or 

```
{
    "use": ["postcss-uncss", "cssnano"],
    "output": "_includes/main.css",
    "autoprefixer": {
        "browsers": "> 5%"
    },
    "postcss-uncss": {
	"html": ["http://localhost:4000"],
	"media": ["(min-width: 768px)", "(min-width: 992px)", "(min-width: 1200px)"]
    }
}
```

Unfortunately media queries are removed from output css in both cases.

**Comment by RyanZim** [comment]
@marcinant When using uncss as a postcss plugin, uncss will not extract the stylesheets from your html, so the `media` option is unnecessary. Here is the correct setup:
```
{
    "use": ["postcss-uncss", "cssnano"],
    "output": "_includes/main.css",
    "autoprefixer": {
        "browsers": "> 5%"
    },
    "postcss-uncss": {
    "html": ["http://localhost:4000"]
    }
}
```
Then run `postcss path/to/css/folder/*.css -c postcss.json`.
