### ISSUE TITLE
uncssrc doesn't seem to work

### ISSUE THREAD

**Issue by etylsarin** [RyanZim/postcss-uncss#4]
Hi,

I would like to use .uncssrc file to define a list of ignored patterns.
However, even when I set uncssrc: '.uncssrc' in the options object, it doesn't seem to affect the uncss process.
Could you please help me out?

Thanks!

**Comment by RyanZim** [comment]
`postcss-uncss` doesn't support `.uncssrc` files; you have to pass the `ignore` option directly to `postcss-uncss`. If you can tell me what postcss runner you're using, I can try to show you an example.

**Comment by etylsarin** [comment]
ok, thanks. I use gulp and also know how to set the ignore list there. However I would like to abstract the gulpfile so it doesn't contain specific regex patterns, the rc file seems to be a better place to me.
If you could pass uncssrc option to the uncss as you do it with html and ignore, that would be great.
